### ISSUE TITLE
Validity flags correctness

### ISSUE THREAD

**Issue by fab1an** [SMerrony/tello#13]
Is this correct, you have Y ordered before X.
Also there is an "unused" bit between velocity and position validity. Is it really packed like this?

https://github.com/SMerrony/tello/blob/a195b6550ebf8e7c16fffd043bbd021eef272de2/messages.go#L275

**Comment by SMerrony** [comment]
It might not be correct.  It's been a while since I looked at the Tello stuff, but I remember when we were trying to reverse-engineer these messages there was a lot of discussion about the order of X, Y, & Z values throughout the API.  

With the current code it doesn't matter as the three flags are only used together - that was a deliberate decision as it seemed that if any value was invalid then the others could not be trusted.

If you are sure it's wrong then of course I'll change it!

Also, there are quite a few 'gaps' in the data packing - they may or may not contain more information.  At the time we had no way of decoding them.

**Comment by fab1an** [comment]
Ok, thanks.
